name: 'Setup Vim'
author: 'rhysd <https://rhysd.github.io>'
description: 'Setup Vim or Neovim text editors on GitHub Actions'
branding:
  icon: 'edit'
  color: 'green'

inputs:
  version:
    description: >
      Version of Vim or Neovim to install. Valid values are 'stable', 'nightly' or version tag such
      as 'v8.2.0126'. Note that this value must exactly match to a tag name when installing the
      specific version.
    required: false
    default: 'stable'
  neovim:
    description: >
      Setting to true will install Neovim.
    required: false
    default: false
  configure-args:
    description: >
      Arguments passed to ./configure execution when building Vim from source.
    required: false
  token:
    description: >
      Personal access token for GitHub API. It is used for calling GitHub API when Neovim asset is
      not found in stable releases and needs to fallback. You don't need to set this input since it
      is set automatically.
    default: ${{ github.token }}

outputs:
  executable:
    description: >
      Absolute file path to the installed executable.
  vim-dir:
    description: >
      Absolute file path to the $VIM directory of the installation. Please see `:help $VIM` for
      more details.

runs:
  using: 'node24'
  main: 'src/index.js'
